# Generated by Django 5.2.10 on 2026-02-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccesslog_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin - Acesso Total'), ('noc', 'NOC - Operacional'), ('leitura', 'Leitura - Somente Visualizar')], default='leitura', max_length=20, verbose_name='Nivel de Acesso'),
        ),
    ]
