# Generated by Django 5.2.10 on 2026-02-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_useraccesslog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccesslog',
            name='ssh_command',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccesslog',
            name='ssh_device',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraccesslog',
            name='ssh_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccesslog',
            name='ssh_success',
            field=models.BooleanField(default=True),
        ),
    ]
