# Generated by Django 5.2.10 on 2026-02-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_useraccesslog_ssh_command_useraccesslog_ssh_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
