# Generated by Django 5.2.10 on 2026-02-09 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('vendor', models.CharField(default='Huawei', max_length=100)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.IntegerField(default=22)),
                ('protocol', models.CharField(choices=[('SSH', 'SSH'), ('Telnet', 'Telnet')], default='SSH', max_length=10)),
                ('snmp_community', models.CharField(default='Visiononline1', max_length=100)),
                ('snmp_port', models.IntegerField(default=161)),
                ('snmp_version', models.CharField(default='v2c', max_length=10)),
                ('is_bras', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('backup_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'devices_device',
            },
        ),
        migrations.CreateModel(
            name='DeviceBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_text', models.TextField()),
                ('status', models.CharField(default='success', max_length=50)),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'db_table': 'devices_devicebackup',
            },
        ),
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'db_table': 'devices_devicehistory',
            },
        ),
        migrations.CreateModel(
            name='InterfaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=100)),
                ('rx_value', models.BigIntegerField()),
                ('tx_value', models.BigIntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'db_table': 'devices_interfacedata',
            },
        ),
        migrations.CreateModel(
            name='TerminalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices_terminallog',
            },
        ),
    ]
