# Generated by Django 5.2.10 on 2026-02-10 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicehistory',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='interfacedata',
            old_name='interface',
            new_name='interface_name',
        ),
        migrations.RenameField(
            model_name='terminallog',
            old_name='start_time',
            new_name='executed_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='devicebackup',
            name='config_text',
        ),
        migrations.RemoveField(
            model_name='devicebackup',
            name='size',
        ),
        migrations.RemoveField(
            model_name='devicehistory',
            name='action',
        ),
        migrations.RemoveField(
            model_name='interfacedata',
            name='rx_value',
        ),
        migrations.RemoveField(
            model_name='interfacedata',
            name='tx_value',
        ),
        migrations.RemoveField(
            model_name='terminallog',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='terminallog',
            name='user',
        ),
        migrations.AddField(
            model_name='device',
            name='backup_method',
            field=models.CharField(default='ssh_cli', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='device',
            name='librenms_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='os_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='uptime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicebackup',
            name='file_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicehistory',
            name='description',
            field=models.TextField(default='timezone.now'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicehistory',
            name='event_type',
            field=models.CharField(default='SYSTEM', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interfacedata',
            name='traffic_in',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interfacedata',
            name='traffic_out',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interfacedata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='terminallog',
            name='output',
            field=models.TextField(default='legacy_output'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='protocol',
            field=models.CharField(default='SSH', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='snmp_community',
            field=models.CharField(default='public', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(default='Generic', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicebackup',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='device',
            table=None,
        ),
        migrations.AlterModelTable(
            name='devicebackup',
            table=None,
        ),
        migrations.AlterModelTable(
            name='devicehistory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='interfacedata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='terminallog',
            table=None,
        ),
    ]
