# Generated by Django 5.2.10 on 2026-02-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_rename_timestamp_devicehistory_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='backup_method',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='device',
            name='uptime',
        ),
        migrations.AddField(
            model_name='device',
            name='backup_frequency',
            field=models.CharField(default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='backup_time',
            field=models.TimeField(default='03:00'),
        ),
        migrations.AlterField(
            model_name='device',
            name='librenms_id',
            field=models.IntegerField(blank=True, help_text='ID numérico no LibreNMS (Ex: 2)', null=True),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='event_type',
            field=models.CharField(default='SYSTEM', max_length=50),
        ),
        migrations.AlterField(
            model_name='terminallog',
            name='command',
            field=models.TextField(default='legacy_command'),
        ),
        migrations.AlterField(
            model_name='terminallog',
            name='output',
            field=models.TextField(default='legacy_output'),
        ),
    ]
