# Generated by Django 5.2.10 on 2026-02-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_terminalsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='web_url',
            field=models.CharField(blank=True, help_text='Ex: https://10.0.0.1:8443', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='librenms_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
