# Generated by Django 5.2.10 on 2026-02-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_web_url_alter_device_librenms_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminalsession',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='device',
            name='snmp_community',
            field=models.CharField(default='Visiononline1', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(default='Huawei', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='web_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
