# Generated by Django 5.2.10 on 2026-03-02 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_remove_terminalsession_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassCommandScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Script')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('vendor', models.CharField(choices=[('all', 'Todos'), ('Mikrotik', 'Mikrotik'), ('Huawei', 'Huawei'), ('Juniper', 'Juniper'), ('FiberHome', 'FiberHome OLT'), ('Linux', 'Linux/Ubuntu/Debian'), ('Windows', 'Windows Server')], default='all', max_length=50, verbose_name='Vendor Alvo')),
                ('commands', models.TextField(verbose_name='Comandos (um por linha)')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='Variaveis')),
                ('timeout', models.IntegerField(default=30, verbose_name='Timeout (segundos)')),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Script de Comando',
                'verbose_name_plural': 'Scripts de Comandos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MassCommandExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Agendado para')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('completed', 'Concluido'), ('partial', 'Parcialmente Concluido'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('triggered_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devices', models.ManyToManyField(related_name='command_executions', to='devices.device')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='devices.masscommandscript')),
            ],
            options={
                'verbose_name': 'Execucao de Comando',
                'verbose_name_plural': 'Execucoes de Comandos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MassCommandResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('output', models.TextField(blank=True, verbose_name='Saida do comando')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('execution_time', models.FloatField(default=0, verbose_name='Tempo de execucao (s)')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='devices.masscommandexecution')),
            ],
            options={
                'verbose_name': 'Resultado de Comando',
                'verbose_name_plural': 'Resultados de Comandos',
                'unique_together': {('execution', 'device')},
            },
        ),
    ]
