# Generated by Django 5.2.10 on 2026-03-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_mass_commands'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masscommandexecution',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='masscommandresult',
            options={},
        ),
        migrations.AlterModelOptions(
            name='masscommandscript',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='masscommandexecution',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masscommandexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('completed', 'Concluido'), ('partial', 'Parcial'), ('failed', 'Falhou')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='masscommandresult',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='masscommandresult',
            name='execution_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='masscommandresult',
            name='output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='masscommandscript',
            name='commands',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='masscommandscript',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='masscommandscript',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='masscommandscript',
            name='timeout',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='masscommandscript',
            name='variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='masscommandscript',
            name='vendor',
            field=models.CharField(choices=[('all', 'Todos'), ('Mikrotik', 'Mikrotik'), ('Huawei', 'Huawei'), ('Juniper', 'Juniper'), ('FiberHome', 'FiberHome OLT'), ('Linux', 'Linux/Ubuntu/Debian'), ('Windows', 'Windows Server')], default='all', max_length=50),
        ),
    ]
