# Generated by Django 5.2.10 on 2026-03-12 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_mass_commands'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('OLT', 'OLT'), ('Switch', 'Switch'), ('Router', 'Router'), ('Concentrador', 'Concentrador (BNG/BRAS/PPPoE)'), ('CGNAT', 'CGNAT'), ('ONU', 'ONU'), ('ONT', 'ONT'), ('Wireless', 'Wireless'), ('Server', 'Server'), ('Outro', 'Outro')], default='Router', max_length=30),
        ),
        migrations.AddField(
            model_name='device',
            name='icmp_latency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='icmp_packet_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='icmp_status',
            field=models.CharField(choices=[('online', 'Online'), ('warning', 'Warning'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='last_icmp_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(choices=[('Huawei', 'Huawei'), ('Mikrotik', 'Mikrotik'), ('FiberHome', 'FiberHome'), ('Juniper', 'Juniper'), ('Cisco', 'Cisco'), ('TP-Link', 'TP-Link'), ('Ubiquiti', 'Ubiquiti'), ('Fortinet', 'Fortinet'), ('HP/Aruba', 'HP/Aruba'), ('Dell', 'Dell'), ('Linux', 'Linux'), ('Windows', 'Windows'), ('Outro', 'Outro')], default='Huawei', max_length=50),
        ),
        migrations.CreateModel(
            name='ICMPCheckHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('packets_sent', models.IntegerField(default=5)),
                ('packets_received', models.IntegerField(default=0)),
                ('packet_loss', models.FloatField(default=0)),
                ('min_latency', models.FloatField(default=0)),
                ('avg_latency', models.FloatField(default=0)),
                ('max_latency', models.FloatField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icmp_history', to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_index', models.IntegerField()),
                ('if_name', models.CharField(max_length=100)),
                ('if_alias', models.CharField(blank=True, max_length=255, null=True)),
                ('if_descr', models.TextField(blank=True, null=True)),
                ('if_admin_status', models.CharField(default='down', max_length=20)),
                ('if_oper_status', models.CharField(default='down', max_length=20)),
                ('if_speed', models.BigIntegerField(default=0)),
                ('if_mtu', models.IntegerField(default=1500)),
                ('if_type', models.CharField(blank=True, max_length=50, null=True)),
                ('traffic_in', models.BigIntegerField(default=0)),
                ('traffic_out', models.BigIntegerField(default=0)),
                ('has_gbic', models.BooleanField(default=False)),
                ('gbic_type', models.CharField(blank=True, max_length=100, null=True)),
                ('gbic_vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('gbic_part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('gbic_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('gbic_wavelength', models.CharField(blank=True, max_length=50, null=True)),
                ('rx_power', models.FloatField(blank=True, null=True)),
                ('tx_power', models.FloatField(blank=True, null=True)),
                ('rx_power_high_alert', models.FloatField(default=-10)),
                ('rx_power_low_alert', models.FloatField(default=-25)),
                ('tx_power_high_alert', models.FloatField(default=-3)),
                ('tx_power_low_alert', models.FloatField(default=-10)),
                ('librenms_port_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='devices.device')),
            ],
            options={
                'ordering': ['if_name'],
                'unique_together': {('device', 'if_index')},
            },
        ),
    ]
