# Generated by Django 5.2.10 on 2026-03-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_add_device_type_icmp_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinterface',
            name='gbic_bias_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceinterface',
            name='gbic_channels',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deviceinterface',
            name='gbic_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceinterface',
            name='gbic_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
