# Generated by Django 5.2.10 on 2026-03-15 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_deviceinterface_gbic_bias_current_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_id', models.CharField(max_length=50, unique=True)),
                ('widget_type', models.CharField(choices=[('pie_chart', 'Grafico de Pizza'), ('bar_chart', 'Grafico de Barras'), ('line_chart', 'Grafico de Linha'), ('gauge', 'Medidor/Gauge'), ('big_number', 'Numero Grande'), ('status_card', 'Card de Status'), ('power_meter', 'Medidor de Potencia Optica'), ('server_health', 'Saude do Servidor'), ('table', 'Tabela de Dados'), ('ddm_summary', 'Resumo DDM'), ('device_status', 'Status de Dispositivo'), ('interface_stats', 'Estatisticas de Interface')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('grid_x', models.IntegerField(default=0)),
                ('grid_y', models.IntegerField(default=0)),
                ('grid_w', models.IntegerField(default=2)),
                ('grid_h', models.IntegerField(default=1)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('data_source', models.CharField(blank=True, max_length=50)),
                ('device_filter', models.IntegerField(blank=True, null=True)),
                ('interface_filter', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('refresh_seconds', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['grid_y', 'grid_x'],
            },
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_config', models.JSONField(blank=True, default=dict)),
                ('is_customized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_x', models.IntegerField(blank=True, null=True)),
                ('grid_y', models.IntegerField(blank=True, null=True)),
                ('grid_w', models.IntegerField(blank=True, null=True)),
                ('grid_h', models.IntegerField(blank=True, null=True)),
                ('custom_config', models.JSONField(blank=True, default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.dashboardwidget')),
            ],
            options={
                'unique_together': {('user', 'widget')},
            },
        ),
    ]
