# Generated by Django 5.2.10 on 2026-03-15 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_dashboard_widgets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GBICAlarmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_warning', models.FloatField(default=45.0)),
                ('temp_critical', models.FloatField(default=60.0)),
                ('rx_warning', models.FloatField(default=-20.0)),
                ('rx_critical', models.FloatField(default=-25.0)),
                ('tx_warning', models.FloatField(default=0.0)),
                ('tx_critical', models.FloatField(default=-5.0)),
                ('rx_variation_alert', models.FloatField(default=5.0, help_text='Alertar se RX variar mais que X dB')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_config', to='devices.deviceinterface')),
            ],
            options={
                'verbose_name': 'Configuracao de Alarme GBIC',
                'db_table': 'devices_gbic_alarm_config',
            },
        ),
        migrations.CreateModel(
            name='UserMonitoredGBIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.deviceinterface')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GBIC Monitorado pelo Usuario',
                'db_table': 'devices_user_monitored_gbic',
                'unique_together': {('user', 'interface')},
            },
        ),
    ]
