# Generated by Django 5.2.10 on 2026-01-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(default='corporate', max_length=20),
        ),
    ]
