# Generated by Django 5.2.10 on 2026-01-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0002_alter_userprofile_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_interval', models.IntegerField(default=1, verbose_name='Intervalo de Monitoramento (min)')),
                ('scan_enabled', models.BooleanField(default=True, verbose_name='Monitoramento Ativo')),
                ('inventory_interval', models.IntegerField(default=24, verbose_name='Intervalo de Inventário (horas)')),
                ('inventory_enabled', models.BooleanField(default=True, verbose_name='Inventário Ativo')),
                ('show_total_card', models.BooleanField(default=True, verbose_name='Mostrar Card Total')),
                ('show_online_card', models.BooleanField(default=True, verbose_name='Mostrar Card Online')),
                ('show_offline_card', models.BooleanField(default=True, verbose_name='Mostrar Card Offline')),
                ('show_backup_card', models.BooleanField(default=True, verbose_name='Mostrar Card Backup')),
            ],
        ),
    ]
