# Generated by Django 5.2.10 on 2026-02-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0003_systemsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
