# Generated by Django 5.2.10 on 2026-02-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_system', '0004_delete_systemsettings_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_warning_threshold', models.IntegerField(default=80, verbose_name='Alerta CPU Alta (%)')),
                ('cpu_critical_threshold', models.IntegerField(default=95, verbose_name='Crítico CPU (%)')),
                ('pppoe_drop_alert', models.IntegerField(default=50, verbose_name='Alerta Queda PPPoE (Qtd)')),
                ('ping_timeout', models.IntegerField(default=2, verbose_name='Timeout Ping (segundos)')),
                ('telegram_enabled', models.BooleanField(default=False, verbose_name='Ativar Telegram')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=200, verbose_name='Bot Token')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, verbose_name='Chat ID')),
                ('keep_logs_days', models.IntegerField(default=30, verbose_name='Manter Logs por (dias)')),
                ('keep_backups_days', models.IntegerField(default=90, verbose_name='Manter Backups por (dias)')),
                ('system_name', models.CharField(default='LOR CGR', max_length=50, verbose_name='Nome do Sistema')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Modo Manutenção')),
            ],
        ),
    ]
