# Generated by Django 5.2.10 on 2026-02-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ai_enabled',
            field=models.BooleanField(default=True, verbose_name='Ativar Assistente IA'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_max_tokens',
            field=models.IntegerField(default=4096, verbose_name='Max Tokens'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_provider',
            field=models.CharField(default='groq', max_length=50, verbose_name='Provedor IA'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_temperature',
            field=models.FloatField(default=0.7, verbose_name='Temperatura'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='groq_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Groq API Key'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='groq_model',
            field=models.CharField(default='llama-3.3-70b-versatile', max_length=100, verbose_name='Modelo Groq'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='librenms_api_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='API Token'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='librenms_enabled',
            field=models.BooleanField(default=True, verbose_name='Ativar LibreNMS'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='librenms_url',
            field=models.CharField(default='http://localhost:8081', max_length=255, verbose_name='URL LibreNMS'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='phpipam_app_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='App ID'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='phpipam_app_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='App Key'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='phpipam_enabled',
            field=models.BooleanField(default=True, verbose_name='Ativar phpIPAM'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='phpipam_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Senha'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='phpipam_url',
            field=models.CharField(default='http://localhost:9100', max_length=255, verbose_name='URL phpIPAM'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='phpipam_user',
            field=models.CharField(blank=True, max_length=50, verbose_name='Usuário'),
        ),
    ]
