# Generated by Django 5.2.10 on 2026-02-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0006_add_integrations_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ai_system_prompt',
            field=models.TextField(default='Você é um assistente especializado em redes e infraestrutura de TI. Ajude com configurações de roteadores, switches, diagnóstico de problemas de rede, e melhores práticas de infraestrutura.', verbose_name='Prompt do Sistema'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='git_auto_backup',
            field=models.BooleanField(default=False, verbose_name='Backup Automático'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='git_backup_frequency',
            field=models.CharField(default='daily', max_length=20, verbose_name='Frequência'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='git_branch',
            field=models.CharField(default='main', max_length=50, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='git_enabled',
            field=models.BooleanField(default=False, verbose_name='Ativar Backup Git'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='git_repo_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL do Repositório'),
        ),
    ]
