# Generated by Django 5.2.10 on 2026-02-27 00:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0007_add_prompt_git_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='ai_max_tokens',
            field=models.IntegerField(default=4096),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='ai_provider',
            field=models.CharField(default='groq', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='ai_system_prompt',
            field=models.TextField(default='Voce e um assistente especializado em redes e infraestrutura de TI.'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='ai_temperature',
            field=models.FloatField(default=0.7),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='cpu_critical_threshold',
            field=models.IntegerField(default=95),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='cpu_warning_threshold',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='git_auto_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='git_backup_frequency',
            field=models.CharField(default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='git_branch',
            field=models.CharField(default='main', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='git_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='git_repo_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='groq_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='groq_model',
            field=models.CharField(default='llama-3.3-70b-versatile', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='keep_backups_days',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='keep_logs_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='librenms_api_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='librenms_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='librenms_url',
            field=models.CharField(default='http://localhost:8081', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='phpipam_app_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='phpipam_app_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='phpipam_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='phpipam_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='phpipam_url',
            field=models.CharField(default='http://localhost:9100', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='phpipam_user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='ping_timeout',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='pppoe_drop_alert',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='system_name',
            field=models.CharField(default='LOR CGR', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='telegram_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='Nova Conversa', max_length=200)),
                ('context', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Assistente'), ('system', 'Sistema'), ('tool', 'Ferramenta')], max_length=20)),
                ('content', models.TextField()),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tool_args', models.JSONField(blank=True, null=True)),
                ('tool_result', models.JSONField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core_system.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
