# Generated by Django 5.2.10 on 2026-02-11 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT-4)'), ('google', 'Google (Gemini)'), ('cohere', 'Cohere'), ('local', 'LLM Local (Ollama)')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_url', models.URLField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('max_tokens', models.IntegerField(default=4000)),
                ('temperature', models.FloatField(default=0.7)),
                ('required_packages', models.JSONField(blank=True, default=list)),
                ('packages_installed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provedor de IA',
                'verbose_name_plural': 'Provedores de IA',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_ai_assistant', models.BooleanField(default=True)),
                ('enable_streaming', models.BooleanField(default=True)),
                ('librenms_url', models.URLField(blank=True, null=True)),
                ('librenms_token', models.CharField(blank=True, max_length=500)),
                ('phpipam_url', models.URLField(blank=True, null=True)),
                ('phpipam_token', models.CharField(blank=True, max_length=500)),
                ('active_ai_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_system', to='ai_assistant.aiprovider')),
            ],
            options={
                'verbose_name': 'Configurações do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark-blue', 'Azul Escuro (Padrão)'), ('dark-purple', 'Roxo Escuro'), ('dark-green', 'Verde Escuro'), ('cyberpunk', 'Cyberpunk (Neon)'), ('minimalist', 'Minimalista Claro'), ('nord', 'Nord (Azul Gelo)')], default='dark-blue', max_length=50)),
                ('dashboard_layout', models.JSONField(blank=True, default=dict)),
                ('ai_streaming_enabled', models.BooleanField(default=True)),
                ('ai_show_tool_calls', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferências do Usuário',
                'verbose_name_plural': 'Preferências dos Usuários',
            },
        ),
    ]
