# Generated by Django 5.2.10 on 2026-01-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhpipamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Servidor Principal', max_length=50)),
                ('url', models.URLField(help_text='Ex: http://45.71.243.138/api/')),
                ('app_id', models.CharField(help_text='O App ID criado no PHPIPAM', max_length=100)),
                ('api_token', models.CharField(help_text='App Code / Token', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração PHPIPAM',
                'verbose_name_plural': 'Configurações PHPIPAM',
            },
        ),
    ]
